### ISSUE TITLE
msg2eml / msg2mbox - "quoted-printable" chars are all the same in html

### ISSUE THREAD

**Issue by datsteves** [lolo101/MsgViewer#152]
Hey, me again.
we got hands on a rather weird msg (actually multiple) where umlaute, or any char that needs to be encoded slightly differently, is correct in the RTF and text portion, but the HTML gets them all encoded with the same char.
for example, in the text, there is 
```
Mit freundlichen Gr=C3=BC=C3=9Fen

Herr Sch=C3=A4fer
```
which will result in 
```
Mit freundlichen Grüßen

Herr Schäfer
```

but in the HTML, it then looks like
```
Mit freundlichen Gr=EF=BF=BD=EF=BF=BDen

Herr Sch=EF=BF=BDfer
```
as you can see, it has always `=EF=BF=BD` set instead of the actual encoded version. if you then display the HTML, it looks like 
![image](https://user-images.githubusercontent.com/31381383/204521870-e0ee5b6e-b3b0-4fcf-8374-651bcae7406f.png)

this happens when you use the GUI version and select text too.

let me know if you need the msg, as that msg, in particular, shouldn't be shared (that) publically 😅 maybe you already have an idea of what might be the issue here.

**Comment by lolo101** [comment]
Hi @datsteves and thank you for the report!

For the moment I'll investigate using the sample you just gave.
I'll let you know asap!

**Comment by lolo101** [comment]
`=EF=BF=BD` is the UTF-8 encoding for the Unicode character `FFFD` which is the replacement character "�"
So the character is correctly rendered in HTML.
@datsteves was the original message produced with MSGViewer?
If the original message has an HTML part with erroneous characters I'm afraid there is nothing much MSGViewer can do about it

https://fr.wikipedia.org/wiki/Table_des_caract%C3%A8res_Unicode/UFFF0

**Comment by datsteves** [comment]
@lolo101 extended the link. any idea on this?

**Comment by lolo101** [comment]
Hi @datsteves 
I already downloaded the file and reproduced the issue.
For the moment I could not find a clue about the cause of the issue

**Comment by lolo101** [comment]
Ok just realized something unexpected
In the GUI when you check the "Text" radio button, the HTML content is rendered. I should fix the button label :smile: 

What I understand so far: the message's RTF and text content are correct. The HTML content contains Unicode characters encoded in UTF-8 whereas Windows-1252 encoding is expected.

I keep on investigating. Thank you very much for your patience :)

**Comment by lolo101** [comment]
Ok I believe the issue is in class `com.auxilii.msgparser.Message`

This instruction:
```java
case PidTagHtml:
    this.setBodyHtml(new String((byte[]) property.getValue(), StandardCharsets.UTF_8));
    break;
```
assumes the HTML body is encoded in UTF-8 whereas it is encoded in Windows-1252

**Comment by lolo101** [comment]
I confirm: when I change the hardcoded encoding from UTF-8 to ISO-8859-1 the message displays correctly.

I'm now trying to find a way to parse HTML content without presuming its encoding. Maybe using Jericho API right into the Message class?

**Comment by lolo101** [comment]
Hi @datsteves!

I'm pleased to announce that this bug seems fixed (looks ok on my machine :wink:)
Could you confirm it's ok for you?

**Comment by datsteves** [comment]
hey @lolo101 
in the viewer itself it does look right, but when using the CLI with `-msg2eml` then its still not working as expected.
The text version looks fine to me, as the right headers and so on. but the HTML version seems a little off. 
the header states
```
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
```
but the body actually uses charset=ISO-8859-1
as an `ü` is there `=FC` but in utf-8 it should be `=C3=BC` (which is how it is in the text version)

checked the de-/en-coding it with 
https://dencode.com/string/quoted-printable
<img width="508" alt="image" src="https://user-images.githubusercontent.com/31381383/227530742-4a1de5fd-2705-4731-85cf-c0db2675a9d5.png">

otherwise the rest looks good :)

**Comment by lolo101** [comment]
Hm looks like some platform dependant behavior because on my Ubuntu laptop, "ü" is correctly encodes as "=C3=BC".
Anyway I'll look into this. Thanks for the report 🙂

**Comment by lolo101** [comment]
Sorry @datsteves you were absolutely right :slightly_smiling_face: 
After a second look with better conditions, I spotted the issue.

There are several parts in the EML file:
- text/plain
- text/rtf
- text/html

In the text/plain part you can see
```
------=_Part_0_1413730361.1679842721168
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hallo Herr Kl=C3=BCber,
```
Which is correct.

However, the HTML part indicates a UTF-8 encoding while its content is CP-1252 encoded, as you said

I'm working on it!

**Comment by lolo101** [comment]
Hi @datsteves 

Fix for #177 should fix this issue
Do you confirm?

Thank you very much!

**Comment by datsteves** [comment]
hey @lolo101 ,
yes, now everything works as expected on all systems i tested on :)

thank you! ^^
